- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd ~/smartbank-ai
      git pull origin main
      source venv/bin/activate
      pip install -r requirements.txt
      sudo systemctl restart smartbank
      sudo systemctl status smartbank --no-pager
